name: Build-test
on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 0/6 * * *
   inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:     
  MT7621:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment.
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo ${{github.repository}}
          chmod +x ./lede/prevn.sh
          bash ./lede/prevn.sh

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: coolsnowwolf/lede
          fetch-depth: 0
      
      - name: Cache
        uses: 1orz/cacheopenwrt@main
        with:
          ccache: true

      - name: Download and Load custom configuration
        run: |
          curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lede/mt7621/.config >.config
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lede/diy.sh)
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config; make defconfig

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: Download package
        run: |
          make download -j8 >/dev/null 2>&1

      - name: When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo -e "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=sc
          sudo df -h

      - name: Only Upload firmware
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mt7621
          path: bin/targets/*/*

      - name: Upload firmware to Download Station
        if: success()
        run: |
          cd bin/targets/*/*
          zip -r -o -q -9 mt7621.zip . -i *.bin
          curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/lede/XiaoMi/XiaoMi-AC2100" -F "file=@mt7621.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
      
      - name: Remove workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
 
